import './scss/main.scss'
import './images/favicon.png'
import './images/apple-touch-icon.png'
import './images/apple-touch-icon-76x76.png'
import './images/apple-touch-icon-120x120.png'
import './images/apple-touch-icon-144x144.png'
import './images/apple-touch-icon-152x152.png'
import './images/apple-touch-icon-180x180.png'
import './images/logo.png'
import './images/logo-amp.png'
import './images/logo.svg'
import './images/white-logo.png'
import './images/logo_fb.jpg'
import './images/logo_twitter.jpg'
import './images/logo-story-default.jpg'
import './images/logo-gestion-stick.png'
import './images/default-blog.jpg'
import './images/default-sm.png'
import './images/default-md.png'
import './images/default-lg.png'
import './images/web_img_ges_badge2.png'
import './images/plusg.png'
import './images/img_soporte.png'
import './images/signwall/bg_paywall.png'
import './images/signwall/logo_gestion.png'
import './images/signwall/bg_login.png'
import './images/signwall/bg_login.webp'
import './images/signwall/bg_students.png'
import './images/signwall/bg_students.webp'
import './images/author.png'
import './images/arrow-right-2.png'

import '../../../components/utilities/lazyload'

// Imagenes paywall
require.context('./images/paywall', true, /\.(png|webp|jpg|jpeg|gif|svg)$/)
