import './scss/main.scss'
import './images/default-blog.jpg'
import './images/default-sm.png'
import './images/default-md.png'
import './images/default-lg.png'
import './images/logo-white.png'
import './images/logo-blue.png'
import './images/logo-footer-md.png'
import './images/logo-footer-sm.png'
import './images/author.png'

import '../../../components/utilities/lazyload'
