/* eslint-disable max-len */
export default {
  RESIZER_SECRET_KEY:
    '%{AQICAHhcROb/QmeRxNIO1Wz8fwobT+WGv8awlNGG/lOIbIy/mwEez1nS5cgmYn+WwvfOtJ9mAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMX9nUHv48dsfY82ohAgEQgDvEqH0qqPQAuvA9ys76q7ZorQQJk89OUMORKLMiDnVG/mOgm+rxvg7zS/udLNZMsi+S66Gybe3UmRTWSQ==}',
  BLOG_TOKEN:
    '%{AQICAHjsOjPySKOyNi6fCzRsZWdpVLIgdyIpEuNiwK3RkBLYDQFDTlGkQ0WkNiz1Z4Cd1sp1AAAAbzBtBgkqhkiG9w0BBwagYDBeAgEAMFkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM10QelHLInJTtc0R6AgEQgCzLc4wekHJiQWIg7JOKKmjApOovxCSaGVNWN0B1j8vv2PH10Ha3Y+qgnhOBbg==}',
}
