/* eslint-disable max-len */
export default {
  resizerSecret: '%{AQICAHjsOjPySKOyNi6fCzRsZWdpVLIgdyIpEuNiwK3RkBLYDQGyEfMFPWCCFcJ5fXVdSZCxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfBMdqZGxVNdWaJ0rAgEQgDvJwlf0UIjueyZbov9ftTv0RICG1WjaHisabtIGkCbNpB02DAV+XJnVgfwZOYcNS4wr2cdGdUENbr4YeA==}',
  BLOG_TOKEN: '%{AQICAHjsOjPySKOyNi6fCzRsZWdpVLIgdyIpEuNiwK3RkBLYDQFDTlGkQ0WkNiz1Z4Cd1sp1AAAAbzBtBgkqhkiG9w0BBwagYDBeAgEAMFkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM10QelHLInJTtc0R6AgEQgCzLc4wekHJiQWIg7JOKKmjApOovxCSaGVNWN0B1j8vv2PH10Ha3Y+qgnhOBbg==}',
  BLOG_URL_API: '%{AQICAHjsOjPySKOyNi6fCzRsZWdpVLIgdyIpEuNiwK3RkBLYDQH3KxVJsvmCSPJDaXVIFuavAAAAiDCBhQYJKoZIhvcNAQcGoHgwdgIBADBxBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCUjFgPoIicL6vWDRgIBEIBElE8lEfh4iT3s4a1TEZvmpjweEww+BZe7TPiVdcm7+3Vx/KitKhEu5RLCbKJVDoQFSd8pXaVQaiVajgfSWemC1xv19/g=}',
  NEWSLETTER_API: 'https://u32l4eeszh.execute-api.us-east-1.amazonaws.com/prod/emblue/public/v1/subscription',
  ORIGIN_SUSCRIPCIONES: 'https://devpaywall.comerciosuscripciones.pe',
  MIDDLEWARE_TOKEN: 'deb904a03a4e31d420a014534514b8cc8ca4d111',
}
