/* eslint-disable max-len */
export default {
  resizerSecret:
    '%{AQICAHjsOjPySKOyNi6fCzRsZWdpVLIgdyIpEuNiwK3RkBLYDQGyEfMFPWCCFcJ5fXVdSZCxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfBMdqZGxVNdWaJ0rAgEQgDvJwlf0UIjueyZbov9ftTv0RICG1WjaHisabtIGkCbNpB02DAV+XJnVgfwZOYcNS4wr2cdGdUENbr4YeA==}',
  BLOG_TOKEN:
    '%{AQICAHjsOjPySKOyNi6fCzRsZWdpVLIgdyIpEuNiwK3RkBLYDQFDTlGkQ0WkNiz1Z4Cd1sp1AAAAbzBtBgkqhkiG9w0BBwagYDBeAgEAMFkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM10QelHLInJTtc0R6AgEQgCzLc4wekHJiQWIg7JOKKmjApOovxCSaGVNWN0B1j8vv2PH10Ha3Y+qgnhOBbg==}',
  BLOG_URL_API:
    'https://svc-blogs.gestion.pe/apiblogs.php',
  CONTENT_BASE:
    '%{AQICAHjsOjPySKOyNi6fCzRsZWdpVLIgdyIpEuNiwK3RkBLYDQG6yZWKtmlTkiRPx7OCYE2eAAAAyTCBxgYJKoZIhvcNAQcGoIG4MIG1AgEAMIGvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJpmihChLdHxe/owdwIBEICBgRZFexjqovGEahDYO4/8/n4QC0cPrSWGt6v5GBZC2ko4TTw3T0UijwhlXYzfhK53oQgfl8tgEefwhF6gKDobqaigMJZBIwnczdSv8OdEIPO21UsvSjrC91EA+KoIMayCBEUwqaS+Wfor8uMpLxfDKqzq/Z1jkyb4jyB5zHXEyF5q0g==}',
  MIDDLEWARE_BASE_URL: 'http://devpaywall.comerciosuscripciones.pe',
  MIDDLEWARE_TOKEN: 'deb904a03a4e31d420a014534514b8cc8ca4d111',
}
