export const META_ARCHIVE = 'meta_archive'
export const META_AUTHOR = 'meta_author'
export const META_SECTION = 'meta_section'
export const META_STORY = 'meta_story'
export const META_SEARCH = 'meta_search'
export const META_TAG = 'meta_tag'
export const META_HOME = 'meta_home'
