import { Subtype } from 'types/story'

export const SPECIAL: Subtype = 'special'
export const SPECIAL_BASIC: Subtype = 'special_basic'
export const GALLERY_SLIDER: Subtype = 'gallery_slider'
export const GALLERY_VERTICAL: Subtype = 'gallery_vertical'
export const BIG_IMAGE: Subtype = 'image_big'
export const STORY_CORRECTION: Subtype = 'story_correction'
export const WORK_TYPE_REVISION: Subtype = 'work_type_revision'
export const IMAGE_LINK: Subtype = 'image_link'
export const STORY_CUSTOMBLOCK: Subtype = 'story_custom_block'
export const STAMP_TRUST: Subtype = 'stamp_trust'
export const MINUTO_MINUTO: Subtype = 'minuto_minuto'
export const VIDEO_JWPLAYER: Subtype = 'video_jwplayer'
export const VIDEO_JWPLAYER_MATCHING: Subtype = 'video_jwplayer_matching'
export const PARALLAX: Subtype = 'parallax'
