import './scss/main.scss'
import './images/favicon.png'
import './images/apple-touch-icon.png'
import './images/apple-touch-icon-76x76.png'
import './images/apple-touch-icon-120x120.png'
import './images/apple-touch-icon-144x144.png'
import './images/apple-touch-icon-152x152.png'
import './images/apple-touch-icon-180x180.png'
import './images/logo.png'
import './images/logo-amp.png'
import './images/logo.svg'
import './images/white-logo.png'
import './images/logo_fb.jpg'
import './images/logo_twitter.jpg'
import './images/default-blog.jpg'
import './images/default-sm.png'
import './images/default-md.png'
import './images/default-lg.png'
import './images/author.png'
import './images/bc-tramado-nav.png'
import './images/loader.png'
import './images/arrow-right-2.png'
import './images/seccion.jpg'
import './images/bullet.jpg'
import './images/big-lines.png'
import './images/logo-perucom.png'
import './images/logo_mperu.png'

/** Fonts & icons */
import './icons/fonts/default.woff'
import './icons/fonts/perucom.woff'
import './icons/fonts/default.svg'
import './icons/fonts/perucom.svg'

// import './fonts/fira-sans-v11-latin-500.woff'
// import './fonts/fira-sans-v11-latin-500.woff2'
// import './fonts/fira-sans-v11-latin-700.woff'
// import './fonts/fira-sans-v11-latin-700.woff2'
// import './fonts/fira-sans-v11-latin-800.woff'
// import './fonts/fira-sans-v11-latin-800.woff2'
// import './fonts/fira-sans-v11-latin-regular.woff'
// import './fonts/fira-sans-v11-latin-regular.woff2'
// import './fonts/roboto-v27-latin-700.woff'
// import './fonts/roboto-v27-latin-700.woff2'
// import './fonts/roboto-v27-latin-regular.woff'
// import './fonts/roboto-v27-latin-regular.woff2'

/** Scripts */
