import './scss/main.scss'
import './images/favicon.png'
import './images/apple-touch-icon.png'
import './images/apple-touch-icon-76x76.png'
import './images/apple-touch-icon-120x120.png'
import './images/apple-touch-icon-144x144.png'
import './images/apple-touch-icon-152x152.png'
import './images/apple-touch-icon-180x180.png'
import './images/logo.png'
import './images/white-logo.png'
import './images/logo_fb.jpg'
import './images/logo_twitter.jpg'
import './images/logo-story-default.jpg'
import './images/default-blog.jpg'
import './images/default-sm.png'
import './images/default-md.png'
import './images/default-lg.png'
import './images/logo-footer.png'
import './images/otorongo.png'
import './images/logo-sm.png'
import './images/logo-amp.png'
import './images/logo-peru21-stick.png'
import './images/logo-peru21-214x60.png'
import './images/author.png'
import './images/arrow-right-2.png'
import './images/Logo_P21TV.png'
import './images/Logo_P21TVx2.png'
import './images/logo-peru21.jpg'

/** Fonts & icons */
import './icons/fonts/peru21.svg'
import './icons/fonts/peru21.woff'
import './icons/fonts/default.svg'
import './icons/fonts/default.woff'

import './fonts/OpenSans-Regular-webfont.woff'

/** Scripts */
