import './scss/main.scss'
import './images/favicon.png'
import './images/apple-touch-icon.png'
import './images/apple-touch-icon-76x76.png'
import './images/apple-touch-icon-120x120.png'
import './images/apple-touch-icon-144x144.png'
import './images/apple-touch-icon-152x152.png'
import './images/apple-touch-icon-180x180.png'
import './images/logo.png'
import './images/logo_twitter.jpg'
import './images/logo-story-default.jpg'
import './images/aniversario.svg'
import './images/white-logo.png'
import './images/white-logo.svg'
import './images/default-blog.jpg'
import './images/default-sm.png'
import './images/default-md.png'
import './images/default-lg.png'
import './images/paywall/img_confirmation.png'
import './images/paywall/img_confirmation.webp'
import './images/paywall/img_lector.png'
import './images/paywall/img_lector.webp'
import './images/paywall/bg_planes_10.jpg'
import './images/premium-logo.png'
import './images/author.png'

import './images/paywall/img_corporativo.webp'
import './images/paywall/img_corporativo.png'
import './images/paywall/check2.png'
import './images/paywall/img_soporte.webp'
import './images/paywall/img_soporte.png'
import './images/authorOpinion.png'
import './images/logo-amp.png'
import './images/logo-elcomercio-388x60.png'

import './images/bbc_head_fg.jpg'
import './images/bbc_head.png'
import './images/logo-elcomercio.jpg'

import './images/signwall/bg_paywall.png'
import './images/signwall/logo_elcomercio.png'
import './images/signwall/bg_login.png'

import '../../../components/utilities/lazyload'
