import '../elcomercio/scss/main.scss'
import '../elcomercio/images/favicon.png'
import '../elcomercio/images/apple-touch-icon.png'
import '../elcomercio/images/apple-touch-icon-76x76.png'
import '../elcomercio/images/apple-touch-icon-120x120.png'
import '../elcomercio/images/apple-touch-icon-144x144.png'
import '../elcomercio/images/apple-touch-icon-152x152.png'
import '../elcomercio/images/apple-touch-icon-180x180.png'
import '../elcomercio/images/logo.png'
import '../elcomercio/images/logo_twitter.jpg'
import '../elcomercio/images/logo-story-default.jpg'
import '../elcomercio/images/aniversario.svg'
import '../elcomercio/images/white-logo.png'
import '../elcomercio/images/white-logo.svg'
import '../elcomercio/images/default-blog.jpg'
import '../elcomercio/images/default-sm.png'
import '../elcomercio/images/default-md.png'
import '../elcomercio/images/default-lg.png'
import '../elcomercio/images/premium-logo.png'
import '../elcomercio/images/author.png'
import '../elcomercio/images/authorOpinion.png'
import '../elcomercio/images/logo-amp.png'
import '../elcomercio/images/logo-elcomercio-388x60.png'
import '../elcomercio/images/arrow-right-2.png'
import '../elcomercio/images/logo_fb.jpg'
import '../elcomercio/images/logo-sidebar.png'

import '../elcomercio/images/bbc_head_fg.jpg'
import '../elcomercio/images/bbc_head.png'
import '../elcomercio/images/logo-elcomercio.jpg'
import '../elcomercio/images/signwall/paywall_bg.jpg'
import '../elcomercio/images/signwall/logo_elcomercio.png'
import '../elcomercio/images/signwall/bg_login.jpg'
import '../elcomercio/images/signwall/bg_students.jpg'

/** Images Paywall */
import '../elcomercio/images/img_corporativo.png'
import '../elcomercio/images/img_corporativo.webp'

/** Fonts & icons */
import '../elcomercio/icons/fonts/default.woff'
import '../elcomercio/icons/fonts/comercio.woff'
import '../elcomercio/icons/fonts/default.svg'
import '../elcomercio/icons/fonts/comercio.svg'

import '../elcomercio/fonts/LibreFranklin/libre-franklin-v4-latin-500.woff'
import '../elcomercio/fonts/LibreFranklin/libre-franklin-v4-latin-700.woff'
import '../elcomercio/fonts/NotoSerifSC/noto-serif-sc-v6-latin-500.woff'
import '../elcomercio/fonts/NotoSerifSC/noto-serif-sc-v6-latin-700.woff'

/** Scripts */
