import PropTypes from 'prop-types'

export default PropTypes.shape({
  storyConfig: PropTypes.contentConfig('story').isRequired.tag({
    name: 'Configuración del contenido',
  }),
  design: PropTypes.oneOf(['first', 'second', 'third', 'fourth']).tag({
    name: 'Diseño',
    labels: {
      first: 'Autor+Nota simple', // 1col, 1row, imagen parcial superior, sin subtítulo
      second: 'Autor+Nota doble parcial', // 2col, 1row, imagen parcial derecha, con subtítulo
      third: 'Autor+Nota doble completa', // 2col, 1row, imagen completa derecha, con subtítulo
      fourth: 'Autor+Nota full', // 2col, 2row, imagen parcial superior, con subtítulo
    },
    defaultValue: 'first',
  }),
  sectionField: PropTypes.string.tag({
    name: 'Sección',
    group: 'Editar campos',
    description: 'Dejar vacío para tomar el valor original de la historia.',
  }),
  titleField: PropTypes.string.tag({
    name: 'Título',
    group: 'Editar campos',
    description: 'Dejar vacío para tomar el valor original de la historia.',
  }),
  subTitleField: PropTypes.string.tag({
    name: 'Subtítulo',
    group: 'Editar campos',
    description: 'Dejar vacío para tomar el valor original de la historia.',
  }),
  imgField: PropTypes.string.tag({
    name: 'Imagen',
    group: 'Editar campos',
    description: 'Dejar vacío para tomar el valor original de la historia.',
  }),
  adsSpace: PropTypes.oneOf([
    'none',
    'publirreportaje',
    'auspiciotop1',
    'auspiciotop2',
    'auspiciotop3',
    'daily1',
    'daily2',
    'daily3',
    'catalogo1',
    'catalogo2',
    'zonaauspiciada0',
    'zonaauspiciada1',
    'zonaauspiciada2',
    'zonaauspiciada3',
    'zonaauspiciada4',
    'zonaauspiciada5',
    'zonaauspiciada6',
    'zonaauspiciada7',
    'zonaauspiciada8',
    'zonaauspiciada9',
    'zonaauspiciada10',
    'suplementos',
    'middle1',
    'middle2',
    'caja1',
    'caja2',
    'caja3',
  ]).tag({
    name: 'Espacio',
    group: 'Publicidad',
    labels: {
      none: 'Ninguno',
      publirreportaje: 'publirreportaje',
      auspiciotop1: 'auspiciotop1',
      auspiciotop2: 'auspiciotop2',
      auspiciotop3: 'auspiciotop3',
      daily1: 'daily1',
      daily2: 'daily2',
      daily3: 'daily3',
      catalogo1: 'catalogo1',
      catalogo2: 'catalogo2',
      zonaauspiciada0: 'zonaauspiciada0',
      zonaauspiciada1: 'zonaauspiciada1',
      zonaauspiciada2: 'zonaauspiciada2',
      zonaauspiciada3: 'zonaauspiciada3',
      zonaauspiciada4: 'zonaauspiciada4',
      zonaauspiciada5: 'zonaauspiciada5',
      zonaauspiciada6: 'zonaauspiciada6',
      zonaauspiciada7: 'zonaauspiciada7',
      zonaauspiciada8: 'zonaauspiciada8',
      zonaauspiciada9: 'zonaauspiciada9',
      zonaauspiciada10: 'zonaauspiciada10',
      suplementos: 'suplementos',
      middle1: 'middle1',
      middle2: 'middle2',
      middle3: 'middle3',
      caja1: 'caja1',
      caja2: 'caja2',
      caja3: 'caja3',
    },
    defaultValue: 'none',
  }),
})
