import './scss/main.scss'
import './images/favicon.png'
import './images/apple-touch-icon.png'
import './images/apple-touch-icon-76x76.png'
import './images/apple-touch-icon-120x120.png'
import './images/apple-touch-icon-144x144.png'
import './images/apple-touch-icon-152x152.png'
import './images/apple-touch-icon-180x180.png'
import './images/logo.png'
import './images/logo-amp.png'
import './images/logo_fb.jpg'
import './images/logo_twitter.jpg'
import './images/default-blog.jpg'
import './images/default-sm.png'
import './images/default-md.png'
import './images/default-lg.png'
import './images/author.png'
import './images/alternate-logo.png'
import './images/alternate-logo-w.png'
import './images/bg-link.png'
import './images/arrow-left-circle.png'
import './images/d.png'
import './images/arrow-right-2.png'
import './images/logo-depor.jpg'

/** Fonts & icons */
import './icons/fonts/default.woff'
import './icons/fonts/depor.woff'
import './icons/fonts/default.svg'
import './icons/fonts/depor.svg'

import './fonts/NoticiaText-Bold.woff'
import './fonts/NoticiaText-Regular.woff'
import './fonts/OstrichSans-Bold.woff'
import './fonts/RobotoCondensed-Bold.woff'
import './fonts/RobotoCondensed-Regular.woff'
import './fonts/Saira-Bold.woff'
import './fonts/Saira-Regular.woff'

/** Scripts */
import '../../../components/utilities/grid-to-flex'
