import './scss/main.scss'
import './favicon.ico'
import './images/logo.png'
import './images/default-blog.jpg'
import './images/default-sm.png'
import './images/default-md.png'
import './images/default-lg.png'